services:
  profile-service:
    build:
      context: .
      dockerfile: ./deploy/profile/production/Dockerfile
    image: profile-service:latest
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    environment:
      - CONFIG_FILE=/app/config.json
    volumes:
      - ./deploy/profile/production/config.json:/app/config.json
      - ./migrations/user:/app/migrations/user/
      - ./migrations/rating:/app/migrations/rating/
      - ./data/jwt:/app/jwt/
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.profileservice.rule=PathPrefix(`/profile`)"
      - "traefik.http.routers.profileservice.entrypoints=web"
      - "traefik.http.services.profileservice.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.profile-httpstrip.stripprefix.prefixes=/profile"
      - "traefik.http.routers.profileservice.middlewares=profile-httpstrip"
