services:
  game-service:
    build:
      context: .
      dockerfile: ./deploy/game/production/Dockerfile
    image: game-service:latest
    depends_on:
      redis:
        condition: service_healthy
      broker:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    environment:
      - CONFIG_FILE=/app/config.json
    volumes:
      - ./deploy/game/production/config.json:/app/config.json
      - ./data/jwt:/app/jwt/

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.gameservice.rule=PathPrefix(`/game`)"
      - "traefik.http.routers.gameservice.entrypoints=web"
      - "traefik.http.services.gameservice.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.game-httpstrip.stripprefix.prefixes=/game"
      - "traefik.http.routers.gameservice.middlewares=game-httpstrip"
