services:
  game-service:
    build:
      context: .
      dockerfile: ./deploy/game/production/Dockerfile
    image: game-service:latest
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=./config.json
    volumes:
      - ./deploy/game/production/config.json:/app/config.json
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.httpserver.rule=PathPrefix(`/game`)"
      - "traefik.http.routers.httpserver.entrypoints=web"
      - "traefik.http.services.httpserver.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.httpstrip.stripprefix.prefixes=/game"
      - "traefik.http.routers.httpserver.middlewares=httpstrip"
