services:
  match-service:
    build:
      context: .
      dockerfile: ./deploy/match/production/Dockerfile
    image: match-service:latest
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    environment:
      - CONFIG_FILE=/app/config.json
    volumes:
      - ./deploy/match/production/config.json:/app/config.json
      - ./data/jwt:/app/jwt/
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.matchservice.rule=PathPrefix(`/match`)"
      - "traefik.http.routers.matchservice.entrypoints=web"
      - "traefik.http.services.matchservice.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.match-httpstrip.stripprefix.prefixes=/match"
      - "traefik.http.routers.matchservice.middlewares=match-httpstrip"
