// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: game.proto

package gamepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_GetUserLiveGameID_FullMethodName  = "/game.GameService/GetUserLiveGameID"
	GameService_GetUserLiveGamePGN_FullMethodName = "/game.GameService/GetUserLiveGamePGN"
	GameService_GetLiveGamePGN_FullMethodName     = "/game.GameService/GetLiveGamePGN"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	GetUserLiveGameID(ctx context.Context, in *GetUserLiveGameIdRequest, opts ...grpc.CallOption) (*GetUserLiveGameIdResponse, error)
	GetUserLiveGamePGN(ctx context.Context, in *GetUserLiveGamePgnRequest, opts ...grpc.CallOption) (*GetLiveGamePGNResponse, error)
	GetLiveGamePGN(ctx context.Context, in *GetLiveGamePGNRequest, opts ...grpc.CallOption) (*GetLiveGamePGNResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetUserLiveGameID(ctx context.Context, in *GetUserLiveGameIdRequest, opts ...grpc.CallOption) (*GetUserLiveGameIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLiveGameIdResponse)
	err := c.cc.Invoke(ctx, GameService_GetUserLiveGameID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetUserLiveGamePGN(ctx context.Context, in *GetUserLiveGamePgnRequest, opts ...grpc.CallOption) (*GetLiveGamePGNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLiveGamePGNResponse)
	err := c.cc.Invoke(ctx, GameService_GetUserLiveGamePGN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetLiveGamePGN(ctx context.Context, in *GetLiveGamePGNRequest, opts ...grpc.CallOption) (*GetLiveGamePGNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLiveGamePGNResponse)
	err := c.cc.Invoke(ctx, GameService_GetLiveGamePGN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	GetUserLiveGameID(context.Context, *GetUserLiveGameIdRequest) (*GetUserLiveGameIdResponse, error)
	GetUserLiveGamePGN(context.Context, *GetUserLiveGamePgnRequest) (*GetLiveGamePGNResponse, error)
	GetLiveGamePGN(context.Context, *GetLiveGamePGNRequest) (*GetLiveGamePGNResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) GetUserLiveGameID(context.Context, *GetUserLiveGameIdRequest) (*GetUserLiveGameIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLiveGameID not implemented")
}
func (UnimplementedGameServiceServer) GetUserLiveGamePGN(context.Context, *GetUserLiveGamePgnRequest) (*GetLiveGamePGNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLiveGamePGN not implemented")
}
func (UnimplementedGameServiceServer) GetLiveGamePGN(context.Context, *GetLiveGamePGNRequest) (*GetLiveGamePGNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveGamePGN not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_GetUserLiveGameID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLiveGameIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetUserLiveGameID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetUserLiveGameID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetUserLiveGameID(ctx, req.(*GetUserLiveGameIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetUserLiveGamePGN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLiveGamePgnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetUserLiveGamePGN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetUserLiveGamePGN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetUserLiveGamePGN(ctx, req.(*GetUserLiveGamePgnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetLiveGamePGN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveGamePGNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetLiveGamePGN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetLiveGamePGN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetLiveGamePGN(ctx, req.(*GetLiveGamePGNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserLiveGameID",
			Handler:    _GameService_GetUserLiveGameID_Handler,
		},
		{
			MethodName: "GetUserLiveGamePGN",
			Handler:    _GameService_GetUserLiveGamePGN_Handler,
		},
		{
			MethodName: "GetLiveGamePGN",
			Handler:    _GameService_GetLiveGamePGN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
