// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: wsgateway.proto

package wsgatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WsGatewayService_GetLiveGamesViewersNumber_FullMethodName = "/wsgateway.WsGatewayService/GetLiveGamesViewersNumber"
)

// WsGatewayServiceClient is the client API for WsGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WsGatewayServiceClient interface {
	GetLiveGamesViewersNumber(ctx context.Context, in *LiveGamesViewersNumberRequest, opts ...grpc.CallOption) (*LiveGamesViewersNumberResponse, error)
}

type wsGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWsGatewayServiceClient(cc grpc.ClientConnInterface) WsGatewayServiceClient {
	return &wsGatewayServiceClient{cc}
}

func (c *wsGatewayServiceClient) GetLiveGamesViewersNumber(ctx context.Context, in *LiveGamesViewersNumberRequest, opts ...grpc.CallOption) (*LiveGamesViewersNumberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LiveGamesViewersNumberResponse)
	err := c.cc.Invoke(ctx, WsGatewayService_GetLiveGamesViewersNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WsGatewayServiceServer is the server API for WsGatewayService service.
// All implementations must embed UnimplementedWsGatewayServiceServer
// for forward compatibility.
type WsGatewayServiceServer interface {
	GetLiveGamesViewersNumber(context.Context, *LiveGamesViewersNumberRequest) (*LiveGamesViewersNumberResponse, error)
	mustEmbedUnimplementedWsGatewayServiceServer()
}

// UnimplementedWsGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWsGatewayServiceServer struct{}

func (UnimplementedWsGatewayServiceServer) GetLiveGamesViewersNumber(context.Context, *LiveGamesViewersNumberRequest) (*LiveGamesViewersNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveGamesViewersNumber not implemented")
}
func (UnimplementedWsGatewayServiceServer) mustEmbedUnimplementedWsGatewayServiceServer() {}
func (UnimplementedWsGatewayServiceServer) testEmbeddedByValue()                          {}

// UnsafeWsGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WsGatewayServiceServer will
// result in compilation errors.
type UnsafeWsGatewayServiceServer interface {
	mustEmbedUnimplementedWsGatewayServiceServer()
}

func RegisterWsGatewayServiceServer(s grpc.ServiceRegistrar, srv WsGatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedWsGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WsGatewayService_ServiceDesc, srv)
}

func _WsGatewayService_GetLiveGamesViewersNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiveGamesViewersNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WsGatewayServiceServer).GetLiveGamesViewersNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WsGatewayService_GetLiveGamesViewersNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WsGatewayServiceServer).GetLiveGamesViewersNumber(ctx, req.(*LiveGamesViewersNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WsGatewayService_ServiceDesc is the grpc.ServiceDesc for WsGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WsGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wsgateway.WsGatewayService",
	HandlerType: (*WsGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLiveGamesViewersNumber",
			Handler:    _WsGatewayService_GetLiveGamesViewersNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wsgateway.proto",
}
