version: '3'
services:
  postgres-db:
    image: postgres:12.22
    container_name: postgres-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ../../../authservice/repository/migrations/:/docker-entrypoint-initdb.d
    restart: always
