services:
  auth-service:
    build:
      context: .
      dockerfile: ./deploy/auth/production/Dockerfile
    image: auth-service:latest
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    environment:
      - CONFIG_FILE=/app/config.json
    volumes:
      - ./deploy/auth/production/config.json:/app/config.json
      - ./migrations/auth:/app/migrations/
      - ./data/jwt:/app/jwt/

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.authservice.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.authservice.entrypoints=web"
      - "traefik.http.services.authservice.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.auth-httpstrip.stripprefix.prefixes=/auth"
      - "traefik.http.routers.authservice.middlewares=auth-httpstrip"
