services:
  chat-service:
    build:
      context: .
      dockerfile: ./deploy/chat/production/Dockerfile
    image: chat-service:latest
    depends_on:
      redis:
        condition: service_healthy
      broker:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    environment:
      - CONFIG_FILE=/app/config.json
    volumes:
      - ./deploy/chat/production/config.json:/app/config.json
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.chatservice.rule=PathPrefix(`/chat`)"
      - "traefik.http.routers.chatservice.entrypoints=web"
      - "traefik.http.services.chatservice.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.chat-httpstrip.stripprefix.prefixes=/chat"
      - "traefik.http.routers.chatservice.middlewares=chat-httpstrip"
