services:
  wsgateway:
    build:
      context: .
      dockerfile: ./deploy/wsgateway/production/Dockerfile
    image: wsgateway:latest
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: always
    environment:
      - CONFIG_FILE=/app/config.json
    volumes:
      - ./deploy/wsgateway/production/config.json:/app/config.json
      - ./data/jwt:/app/jwt/
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.wsgateway.rule=PathPrefix(`/wsgateway`)"
      - "traefik.http.routers.wsgateway.entrypoints=web"
      - "traefik.http.services.wsgateway.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.wsgateway-httpstrip.stripprefix.prefixes=/wsgateway"
      - "traefik.http.routers.wsgateway.middlewares=wsgateway-httpstrip"
